Add UnknownType and use in converters
gabledata/recap pull request #430
Opened 2024-03-28 01:19 UTC by mjperrone

Addresses https://github.com/recap-build/recap/issues/429

Adds a new type `UnknownType` for situations where converters can't figure out an appropriate existing recap type.

This does not have comprehensive test cases and I'm not sure this is the right way to go for all these converters, but I wanted to get started on this so we can discuss and collaborate on it.

Made a PR for the website/json schema update:

## Validation

We will need to add a bunch of tests for the converters, parser, and for the JSON schema validation.

2024-03-28 02:18 UTC, criccomini commented
Great, thanks! I'll take a look tomorrow.

One thing I noticed in the website PR was that it seems like you might be modifying the CST to add an "unknown" type. This was something I mentioned wanting to avoid in #429:

> If we went this route, I wouldn't want to add an unknown to the CST, but rather keep UnknownType as only an AST class similar to ProxyType.

I'll take a look and see if we can get away without adding "unknown" as a concrete syntax.

2024-03-28 02:24 UTC, mjperrone commented
Ah yes, forgot/missed that. Thanks for taking a look

2024-03-29 16:18 UTC, criccomini requested changes
Ok! I left some comments. A few notes:

1. I think we should not try to serialize `UnknownType` out to JSON/Proto/Avro. None of those formats support an unknown format. Whatever we do there will break parsers or be pretty hacky.
2. To that end, I also don't believe we should include `"unknown"` in the CST syntax. Do you need this? If so, what is the use case?

I view UnknownType as a way for developers to get a hint that there's a column that couldn't be handled by the converters. The devs are then left with a few options:

a. Strip the `UnknownType`(s) from the recap type (ignore).
b. Raise an error that the converter wasn't able to support all types.
c. Update the converter to properly handle the type.
d. Manually replace the UnknownType with a proper RecapType based on some outside knowledge.

In this philosophy, we don't need an "unknown" CST, and including as much info as possible to the dev via UnknownType's constructor seems like the right path.

2024-03-29 16:18 UTC, criccomini commented on recap/converters/avro.py
> +                avro_schema["type"] = "unknown"
I think we should continue to raise value error here.. "unkonwn" is not a valid Avro schema type. Parsers would fail with this.

2024-03-29 16:18 UTC, criccomini commented on recap/converters/avro.py
> +                return UnknownType(**extra_attrs)
I think we should do `UnknownType(**avro_schema)` rather than extra_attrs. It'd be more useful for debugging to see everything in the Avro schema.

2024-03-29 16:18 UTC, criccomini commented on recap/converters/avro.py
> +                return UnknownType(**extra_attrs)
^ same here

2024-03-29 16:18 UTC, criccomini commented on recap/converters/bigquery.py
> +                    field_type = UnknownType()
Maybe `UnknownType(field_type=field_type)`? I'm thinking we should try to give the dev as much info as possible about the thing we can't convert.

2024-03-29 16:18 UTC, criccomini commented on recap/converters/json_schema.py
> +        if isinstance(recap_schema, UnknownType):
This feels hacky. I think we should probably refactor json_schema to use a similar strategy to the avro converter; namely, creating a _parse that returns `RecapType` and using that in to_recap.

2024-03-29 16:18 UTC, criccomini commented on recap/converters/json_schema.py
> +            case UnknownType():
I feel like we should still raise value error here.. Same as I commented in Avro converter.

2024-03-29 16:18 UTC, criccomini commented on recap/converters/protobuf.py
> +                return UnknownType()
Same here... Probably continue to raise ValueError.

2024-03-29 16:18 UTC, criccomini commented on recap/converters/postgresql.py
> +            base_type = UnknownType()
Incldue `base_type` in unknown type so devs can debug? Any other useful info, too...

2024-03-29 16:18 UTC, criccomini commented on recap/converters/snowflake.py
> +            base_type = UnknownType()
Include data_type

2024-03-29 16:18 UTC, criccomini commented on recap/converters/sqlite.py
> +                return UnknownType()
Include column_* stuff

2024-03-29 16:18 UTC, criccomini commented on recap/types.py
> +    def __init__(self, description: str = "Unknown or unsupported type", **extra_attrs):
Confused by this. RecapType has "doc". Any reason you're not using that?

2024-03-29 16:18 UTC, criccomini commented on recap/types.py
> +    def __eq__(self, other):
Same question for __eq__ and __repr__. RecapType has these already.

2024-03-29 16:18 UTC, criccomini commented on recap/types.py
> +            case "unknown":
This is the part I'd strongly prefer to avoid. I am really nervous about adding `"unknown"` as a type to the CST.

2024-04-30 05:07 UTC, mjperrone commented
I don't think I will be able to make another iteration on this for several more weeks

2024-04-30 22:25 UTC, criccomini commented
No worries, there's nothing pressing on my end.

2025-02-26 18:05 UTC, closed without merging